name: jdbdnz
favicon: null
layout_spectrum: 0.97495
typography_spectrum: 0.91137
title: vanity_schmanity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#92d0f1'
    - '#a19795'
    - '#2c7a99'
    - '#3a3e2b'
    - '#fdf2eb'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
